[package]
name = "frontend"
version = "0.4.0"
edition = "2021"
authors = ["Agustin Marcelo Marco Bacigalupo <01marcoagustin@gmail.com>"]
license = "MIT"

[dependencies]
bridge = { path = "../bridge" }
backend = { path = "../backend" }
iced = { version = "0.8.0", features = ["image", "debug", "tokio", "canvas"] }
iced_native = "0.9.1"
once_cell = "1.17.0"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
