[package]
name = "yama"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
iced_native = "0.8.0"
iced = { version = "0.7", features = ["image", "debug", "tokio"] }
serde_json = "1.0"
serial_test = "0.10.0"
once_cell = "1.17.0"
rand = "0.8.5"
