[package]
name = "yama"
version = "0.4.0"
edition = "2021"
authors = ["Agustin Marcelo Marco Bacigalupo <01marcoagustin@gmail.com>"]
license = "MIT"

[workspace]
members = [
	"backend",
	"frontend",
	"bridge",
]

[dependencies]
frontend = { path = "./frontend" }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }

[workspace.dependencies]
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }

