[package]
name = "backend"
version = "0.4.0"
edition = "2021"
authors = ["Agustin Marcelo Marco Bacigalupo <01marcoagustin@gmail.com>"]
license = "MIT"

[dependencies]
alphanumeric-sort = "1.4.4"
iced = { version = "0.8.0", features = ["tokio"] }
infer = { version = "0.12.0", default-features = false }
once_cell = "1.17.0"
reqwest = { version = "0.11.14", features = ["rustls-tls"] }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.91"
serial_test = "0.10.0"
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
